name: FPPTimer
version: 2.0.0
main: mx.waffles.fpptimer.FPPTimer
api-version: "1.21"
author: Waffles
description: Despawnea bots de FPP automaticamente despues de X tiempo.

commands:
  botdespawn:
    description: Programa el despawn de un bot despues de X tiempo.
    usage: /botdespawn <nombre|all> <tiempo|cancel>
    permission: fpptimer.use
    aliases: [bd]

permissions:
  fpptimer.use:
    description: Permite usar /botdespawn
    default: op
